name: super15
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.4
  google_fonts: ^2.2.0
  sizer: ^2.0.15
  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  flutterfire_cli: ^0.1.1+2
  fluttertoast: ^8.0.8
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.12
  provider: ^6.0.2
  auto_size_text: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  