  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, missing_required_param
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0cyypxAOFzYDFPDZM-MuGG1PP5gIl5k',
    appId: '1:345299748937:web:ff3fea899bfe3e5eefd798',
    messagingSenderId: '345299748937',
    projectId: 'super15-app',
    authDomain: 'super15-app.firebaseapp.com',
    storageBucket: 'super15-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygwSbjivMDZcg_KUeriXjYjetH-ca_G0',
    appId: '1:345299748937:android:347f215cf468f4d4efd798',
    messagingSenderId: '345299748937',
    projectId: 'super15-app',
    storageBucket: 'super15-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA68MTsF6vtfCWYVo-qP0aNkdeqh08VjAI',
    appId: '1:345299748937:ios:a1375aabcdf5dc12efd798',
    messagingSenderId: '345299748937',
    projectId: 'super15-app',
    storageBucket: 'super15-app.appspot.com',
    iosClientId: '345299748937-oo4i4llb8bm85skuf6ea7jlqg4f4fjek.apps.googleusercontent.com',
    iosBundleId: 'com.app.super15',
  );
}
